### ISSUE TITLE
Feedback 2 May 2023

### ISSUE THREAD

**Issue by syahrizalakbar** [dzikrul1616/ProviderCRUD#1]
**Flow tambah data sudah sesuai namun ada beberapa feedback**

1. Untuk tambah pekerjaannya, tombol increment dan decrementnya belum berfungsi
<img width="206" alt="Screenshot 2023-05-02 at 13 29 25" src="https://user-images.githubusercontent.com/27173560/235594708-d1558d40-1e0e-4f9f-81a7-2b1e56782cdf.png">

2. Dihalaman homenya masih terdapat error, dan datanya tidak tampil
<img width="1086" alt="Screenshot 2023-05-02 at 13 31 17" src="https://user-images.githubusercontent.com/27173560/235595163-5b78d4e8-3dce-47ee-a3cf-0ee676c8b3af.png">
<img width="782" alt="Screenshot 2023-05-02 at 13 31 07" src="https://user-images.githubusercontent.com/27173560/235595193-b2a8d5fe-e46f-4fa9-b8ce-481fb3c6e6db.png">

**Untuk Best Practices penulisan codenya ini ada beberapa koreksi :**

1. penamaan file dan folder sebaiknya menggunakan _ untuk memisahkan kata, 
https://dart.dev/guides/language/effective-dart/style#do-name-packages-and-file-system-entities-using-lowercase-with-underscores
<img width="260" alt="Screenshot 2023-05-02 at 13 25 11" src="https://user-images.githubusercontent.com/27173560/235594033-b15a9087-9747-4884-914b-3d5a3f035e03.png">

2. Penamaan class sebaiknya menggunakan UpperCamelCase
https://dart.dev/guides/language/effective-dart/style#do-name-types-using-uppercamelcase
<img width="455" alt="Screenshot 2023-05-02 at 13 24 34" src="https://user-images.githubusercontent.com/27173560/235593949-05ee3eca-e7a8-485d-812c-eec386f600b3.png">

 
4. Penamaan variable sebaiknya menggunakan lowerCamelCase
https://dart.dev/guides/language/effective-dart/style#do-name-other-identifiers-using-lowercamelcase
<img width="387" alt="Screenshot 2023-05-02 at 13 24 10" src="https://user-images.githubusercontent.com/27173560/235593883-f8567782-b11f-4145-ad61-82869bfba4cf.png">
<img width="1074" alt="Screenshot 2023-05-02 at 11 48 42" src="https://user-images.githubusercontent.com/27173560/235593916-0b3c0b21-860f-442a-8907-baf852d3b7c5.png">
  
5. Sebaiknya gunakan nama yang konsisten antara nama class dan nama filenya, misal nama classnya BiodataView, maka nama filenya biodata_view.dart, gunanya agar tidak membingungkan dan lebih mudah dikembangkan jika terdapat lebih dari 1 developer yang mengerjakannya

6. hindari penggunaan ?? pada variable yang tidak akan null
<img width="561" alt="Screenshot 2023-05-02 at 13 23 08" src="https://user-images.githubusercontent.com/27173560/235593737-14a96b8a-6775-4bc7-8df7-758cc6547fc8.png">

**Comment by syahrizalakbar** [comment]
1. Penamaan class sebaiknya menggunakan UpperCamelCase
https://dart.dev/guides/language/effective-dart/style#do-name-types-using-uppercamelcase
<img width="605" alt="Screenshot 2023-05-18 at 14 54 43" src="https://github.com/dzikrul1616/ProviderCRUD/assets/27173560/e1e40957-12b0-45de-83e2-602cba0964e3">

2. Penggunaan delay bukan bukan praktik terbaik untuk menampilkan loading, sebaiknya gunakan loading sesuai dengan selesainya get data, (hint: gunakan variable bool isLoading didalam provider, lalu set true ketika get data, lalu set false jika sudah berhhasil get data, gunakan variable isLoading untuk mengatur tampilan loading )
<img width="625" alt="Screenshot 2023-05-18 at 14 57 08" src="https://github.com/dzikrul1616/ProviderCRUD/assets/27173560/daae51ff-2158-4f22-b889-132c230e3c58">

3. Variable didalam suatu class, sebaaiknya taruh diatas semua
<img width="646" alt="Screenshot 2023-05-18 at 15 00 08" src="https://github.com/dzikrul1616/ProviderCRUD/assets/27173560/43dc2d50-de36-4484-afdf-624ba6a7c09e">

4. Agar code yang dihasilkan bagus, sebaiknya setiap method harus dituliskan dengan lengkap beserta return typenya (Future<void> deleteData..)
<img width="385" alt="Screenshot 2023-05-18 at 15 02 08" src="https://github.com/dzikrul1616/ProviderCRUD/assets/27173560/38ac3dd6-3146-415b-9c01-2382b5ba2c08">

5. Nama folder sebaiknya menggunakan lower case, dan dipisah menggunakan _ jika lebih dari satu kata.
https://dart.dev/guides/language/effective-dart/style#do-name-packages-and-file-system-entities-using-lowercase-with-underscores
<img width="372" alt="Screenshot 2023-05-18 at 15 03 46" src="https://github.com/dzikrul1616/ProviderCRUD/assets/27173560/6c200cc2-e2cf-4449-a55d-eb1366fd26b9">

**Comment by syahrizalakbar** [comment]
5. Nama folder sebaiknya menggunakan lower case, dan dipisah menggunakan _ jika lebih dari satu kata.
https://dart.dev/guides/language/effective-dart/style#do-name-packages-and-file-system-entities-using-lowercase-with-underscores
![](https://user-images.githubusercontent.com/27173560/239177941-6c200cc2-e2cf-4449-a55d-eb1366fd26b9.png)

6. Kode ini kurang efisien, karena akan melakukan get data 2 kali
<img width="408" alt="Screenshot 2023-05-18 at 17 07 25" src="https://github.com/dzikrul1616/ProviderCRUD/assets/27173560/7a6a83ab-78eb-4491-863a-89de85432275">
disini

<img width="474" alt="Screenshot 2023-05-18 at 17 08 13" src="https://github.com/dzikrul1616/ProviderCRUD/assets/27173560/7e138a54-78e3-40a3-9745-f950874f83ef">
dan disini, selain itu notifyListener dibagian init tidak diperlukan, karena sudah ada didalam method getDataid (lagi pula getDataid() itu async jadi perlu diawait jika mau notifyListener setelah getDataid()


<img width="726" alt="Screenshot 2023-05-18 at 17 08 45" src="https://github.com/dzikrul1616/ProviderCRUD/assets/27173560/71bc4591-9def-4d40-968d-3a2c34b1c7d4">
Kode pengecekan seperti ini kurang tepat ya, karena tidak perlu pakai Future builder lagi, jadi sebaiknya seperti ini:

`value.isLoading ? Tampilkan loading : value.users.isEmpty() ? Tampilkan tidak ada data : baru ListView.builder`

**Comment by dzikrul1616** [comment]
Sudah saya fix semua pak beserta bloc & cubit pada branch bloc_cubit
